export default {
  CREATE_PRODUCT: "CREATE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  DECREMENT: "DECREMENT",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
};
